import ClearDay from '../assets/weather-icons/clear-day.svg'
import ClearNight from '../assets/weather-icons/clear-night.svg'
import Cloudy from '../assets/weather-icons/cloudy.svg'
import Fog from '../assets/weather-icons/fog.svg'
import Hail from '../assets/weather-icons/hail.svg'
import PartlyCloudyDay from '../assets/weather-icons/partly-cloudy-day.svg'
import PartlyCloudyNight from '../assets/weather-icons/partly-cloudy-night.svg'
import RainSnowShowersDay from '../assets/weather-icons/rain-snow-showers-day.svg'
import RainSnowShowersNight from '../assets/weather-icons/rain-snow-showers-night.svg'
import RainSnow from '../assets/weather-icons/rain-snow.svg'
import Rain from '../assets/weather-icons/rain.svg'
import ShowersDay from '../assets/weather-icons/showers-day.svg'
import ShowersNight from '../assets/weather-icons/showers-night.svg'
import Sleet from '../assets/weather-icons/sleet.svg'
import SnowShowersDay from '../assets/weather-icons/snow-showers-day.svg'
import SnowShowersNight from '../assets/weather-icons/snow-showers-night.svg'
import Snow from '../assets/weather-icons/snow.svg'
import ThunderRain from '../assets/weather-icons/thunder-rain.svg'
import ThunderShowersDay from '../assets/weather-icons/thunder-showers-day.svg'
import ThunderShowersNight from '../assets/weather-icons/thunder-showers-night.svg'
import Thunder from '../assets/weather-icons/thunder.svg'
import Wind from '../assets/weather-icons/wind.svg'

export default {ClearDay, ClearNight, Cloudy, Fog, Hail, PartlyCloudyDay, PartlyCloudyNight, RainSnowShowersDay, RainSnowShowersNight, RainSnow, Rain, ShowersDay, ShowersNight, Sleet, SnowShowersDay, SnowShowersNight, Snow, ThunderRain, ThunderShowersDay, ThunderShowersNight, Thunder, Wind}